name: Build and Archive macOS App

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ] 

jobs:
  build:
    runs-on: macos-26

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Archive Xcode project
        run: |
          xcodebuild archive \
            -scheme DigitalClock \
            -project DigitalClock.xcodeproj \
            -archivePath ./build/DigitalClock.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      - name: Create .zip from .app
        run: |
          ditto -c -k --sequesterRsrc --keepParent \
          ./build/DigitalClock.xcarchive/Products/Applications/DigitalClock.app \
          DigitalClock.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DigitalClock-macOS 
          path: DigitalClock.zip 
          retention-days: 7 
